// import "./utils/scroll-body.js";
import "./modules/header.js";
import "./modules/transfer.js";
import "./modules/burger.js";
import "./components/scrollToggle.js";
import "./modules/slider.js";
import "./modules/label.js";
import "./utils/form-validation.js";
import "./modules/animations.js";
import ScrollRevealFunc from "./modules/scrollreveal.js";
ScrollRevealFunc();
