// import $ from "jquery";
import "./modules/header.js";
import "./modules/transfer.js";
import "./modules/burger.js";
import "./modules/scroll-button.js";
import "./modules/slider.js";
import "./modules/label.js";
import "./utils/form-validation.js";
// import "./modules/animations.js";
import ScrollReveal from "./modules/scrollreveal.js";
ScrollReveal();
